# Generated by Django 3.2.16 on 2022-12-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('phone', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('sex', models.IntegerField()),
                ('title', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=24)),
                ('permission', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('sex', models.IntegerField()),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=24)),
                ('address', models.CharField(max_length=100)),
                ('permission', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='reg_category',
            fields=[
                ('reg_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.UUIDField(primary_key=True, serialize=False)),
                ('accessToken', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='timeslot',
            fields=[
                ('timeslot_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_uuid', models.UUIDField()),
                ('registration_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.reg_category')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.department')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.patient')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.doctor'),
        ),
        migrations.CreateModel(
            name='breach_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breach_id', models.UUIDField()),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.registration')),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_uuid', models.UUIDField()),
                ('status', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.reg_category')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.department')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.patient')),
            ],
        ),
    ]
