# Generated by Django 3.2.16 on 2022-12-07 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('phone', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=24)),
                ('director', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('sex', models.IntegerField()),
                ('title', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('permission', models.CharField(max_length=10)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.department')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('sex', models.IntegerField()),
                ('identity', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('permission', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pharmaceutical',
            fields=[
                ('pharmaceutical_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('expireddate', models.DateField()),
                ('purchasing_time', models.DateTimeField()),
                ('supplier', models.CharField(max_length=24)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reg_category',
            fields=[
                ('reg_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='timeslot',
            fields=[
                ('timeslot_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('registration_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.reg_category')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.department')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.patient')),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('prescription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.patient')),
            ],
        ),
        migrations.CreateModel(
            name='pre_pha',
            fields=[
                ('pre_pha_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_id', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('pharmaceutical_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.pharmaceutical')),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('notice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=12)),
                ('content', models.TextField()),
                ('isemergency', models.IntegerField()),
                ('towho', models.CharField(max_length=100)),
                ('sendtime', models.DateTimeField()),
                ('expiredtime', models.DateTimeField()),
                ('readnum', models.IntegerField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.users')),
            ],
        ),
        migrations.CreateModel(
            name='medical_record',
            fields=[
                ('medical_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_time', models.DateTimeField()),
                ('symptom', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.patient')),
            ],
        ),
        migrations.CreateModel(
            name='doctor_schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('week', models.CharField(max_length=5)),
                ('time', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('specialist', models.IntegerField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.users'),
        ),
        migrations.CreateModel(
            name='breach_record',
            fields=[
                ('breach_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.registration')),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('registration_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.reg_category')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.department')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.patient')),
                ('prefer_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.timeslot')),
            ],
        ),
    ]
