# Generated by Django 3.2.16 on 2022-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoimsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_role', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='admins',
        ),
        migrations.DeleteModel(
            name='role',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
