# Generated by Django 3.2.16 on 2022-12-08 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoimsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_record',
            name='prescription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.prescription'),
            preserve_default=False,
        ),
    ]
