# Generated by Django 3.2.16 on 2022-12-05 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoimsystem', '0002_auto_20221205_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identity',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
    ]
