# Generated by Django 3.2.16 on 2022-12-08 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hoimsystem', '0002_medical_record_prescription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='charge',
            fields=[
                ('charge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_time', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('status', models.IntegerField()),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.prescription')),
            ],
        ),
    ]
