# Generated by Django 3.2.16 on 2022-12-06 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoimsystem', '0003_patient_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.department'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='doctor_schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoimsystem.doctor')),
            ],
        ),
    ]
