# Generated by Django 3.2.9 on 2022-12-11 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoimsystem', '0004_auto_20221211_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='specialist',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='specialist',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
