# Generated by Django 3.2.16 on 2022-12-07 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoimsystem', '0005_auto_20221206_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_schedule',
            name='date',
        ),
        migrations.AddField(
            model_name='doctor_schedule',
            name='number',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_schedule',
            name='specialist',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_schedule',
            name='time',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_schedule',
            name='week',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
