# Generated by Django 3.2.9 on 2022-12-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoimsystem', '0005_auto_20221211_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='category',
        ),
        migrations.DeleteModel(
            name='reg_category',
        ),
    ]
