# Generated by Django 3.2.16 on 2022-12-07 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoimsystem', '0006_auto_20221207_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='expiredtime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='isemergency',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='readnum',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='sendtime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='towho',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoimsystem.users'),
            preserve_default=False,
        ),
    ]
