# Generated by Django 3.2.9 on 2022-12-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoimsystem', '0007_alter_appointment_prefer_time'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='medical_record',
            name='prescription_id',
        ),

    ]
