# Generated by Django 3.2.16 on 2022-12-07 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hoimsystem', '0007_auto_20221207_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
