<template>
  <div>
    <el-table
      v-loading="listLoading"
      :data="list"
      :element-loading-text="elementLoadingText"
    >
      <el-table-column
        show-overflow-tooltip
        prop="id"
        label="id"
      ></el-table-column>
      <el-table-column
        show-overflow-tooltip
        prop="doctor"
        label="医生"
      ></el-table-column>
      <el-table-column
        show-overflow-tooltip
        prop="inspection"
        label="检查名称"
      ></el-table-column>
      <el-table-column
        show-overflow-tooltip
        prop="time"
        label="检查时间"
      ></el-table-column>
      <el-table-column
        show-overflow-tooltip
        prop="result"
        label="检查结果"
      ></el-table-column>
    </el-table>
  </div>
</template>

<script>
  export default {
    name: 'InspectionPatient',
  }
</script>
